--Criação do banco de dados
CREATE DATABASE WISHLIST;

--Selecionando o banco de dados
USE WISHLIST;

--Criação da tabela de Usuários
CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(255) NOT NULL 
	, EMAIL VARCHAR(255) NOT NULL UNIQUE
	, SENHA VARCHAR(255) NOT NULL
	
);

--Criação da tabela de Desejos

CREATE TABLE DESEJOS(
	 ID INT IDENTITY PRIMARY KEY
	, IDUSUARIO INT FOREIGN KEY REFERENCES USUARIOS (ID)
	, DATACRIACAO DATE NOT NULL
	, DESCRICAO TEXT NOT NULL
	


);


